config/routes.rb
TestingTimes::Application.routes.draw do

  
	# active admin added its own URL's to the site 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # I want to set up all of the url's for the stories controller
  # this is a short cut for adding 7 different actions
  # REST is a way to alter and view data, the 7 actions are
  # index, show, new, create, edit,update, destroy
  # asymbol is a veriable that does not change! : 

  resources :stories do

  	# inside the stories, we have a nested resource whic is a relasionship
  	# between stories and comments. 
  	resources :comments 

    # inside the stories we have another nested resource which is a relationship between stories and votes
    resources :votes
  	
  end

  #new_story_path  --> stories#new
  #edit_story_path --> tories#edit
  #story_path --> stories#show
  # stories_path --> stories#index


  # new_comments_path   --> commentss#new
  # edit_comment_path --> commentss#edit
  #story_comment_path --> commentssshow
  # story_comments_path --> commentss#index



  # set up my home page to go to the stories controller
  # and show the index page 
  root "stories#index"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base


		# let the comment know about the story its attached to 
		belongs_to :story

		# make sure the comment is not blank
		validates :body, presence: true


end

app/models/story.rb
class Story < ActiveRecord::Base


	# lets make the code know the realsionship between story and comment 

	has_many :comments 

	 # add another realtionship between stories and votes 

	 has_many :votes


	# lets make sure our data in our database is exactly what we wnat it to be 

	validates :title, presence: true, 
		length: { minimum: 5, message: "must be over 5 characters long" }

	validates :link, presence: true, uniqueness: true
	 # validates is a method 
	 # :title is a symbol because it does not change within the code 
	 # {presence: trues} is a hash 





end

app/models/vote.rb
class Vote < ActiveRecord::Base


	# let the vote know about the story its attached to ]
	# and let the story keep track of how many votes it has 

	belongs_to :story, counter_cache: true

	# what we want to do is check that the ip address is unique for that storie
	validates :ip_address, uniqueness: { scope: :story_id}

	# if we had just unqueness is true that would mean one vote across the site 
	# per ip address this way we can do one vote per story 


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	# this controller only needs new and create 
	# because we dont want useres to edit delete or vieew a list 

	def new

		# we need to find which story we're talking about
		# and we need to make a new comment on that story

		# we dont want the params id because {:id} because that is talking about a comment NOT A STORY

		# we can get the params id from the URL THROUGH 

		@story = Story.find(params[:story_id])
		@comment = @story.comments.new 
	end

		# actually create the comment on the story

	def create
		#  same line as in the "new"
		@story = Story.find(params[:story_id])
		@comment = @story.comments.new (comment_params)

		# just like with the story controller if the comment is saved then redirect 

		if @comment.save 
			flash[:success] ="your comment has been posted"
			redirect_to story_path(@story)
		else
			render "new"
		end
	end

	#  lets make a short cut for whitelisting our form data

	def comment_params
		# ensure that the body field is filled in case of hackers
		params.require(:comment).permit(:body)

		
	end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

	# To add a page to my site lets add
	# a index page/home page (this is an action)

	def index
		#this is all the code for the index page 
		@username = "Joe"

		#to make a list, we use square brackets quotes means when the page is refreshed content will not change
		#@stories = ["Google", "Facebook", "Twitter", "linklin", "Foursquare"]
		#now we want to get our data from teh database, (to find all from database)
		# if the order by create_at desc
		# elese just do the useal stuff


		if params[:sort] == "recent"
			# if true sort by most recent 
			@stories = Story.order("created_at desc").page(params[:page])


		elsif params[:filter] == "featured"
			
			@stories = Story.where(is_featured: true).order("title asc").page(params[:page])


		else

			# sort by most voted
			@stories = Story.order("votes_count desc, created_at desc").page(params[:page])
		end

		  # @stories = Story.all 
		

		# 
	end 

	#show me  an individual story page
	def show
		@story = Story.find(params[:id])
		
		
	end

	#this is going to be 'adding a new story from' page 
	#params id is from the url e.g if /storires/7 then param[:id] = 7

	def new 
		# make @story be a blank story ready to be filled in
		@story = Story.new 
		
	end


	# new and create work together as a pair the create action actully adds to the database 

	def create

		#Lets make @story be a blank story with fields filled in
		#@story = Story.new(title: "test", description: "test", link: "http://anything.com")
		 

		@story = Story.new(story_params)


		#actully save this story to the database
		# if they dont pass , show the form with some errors 

		if @story.save



			#lets add a notification to the user to let them know it has been saved to the database
			flash[:sucess] = "well done! you story has been submitted"

			# Lets make this go back to the homepage
			redirect_to root_path
		else
			# if the story does not save, do this 
			# show the new.html.erb form with errors
			# new will keep user on the new page and keep information in the form 
			render "new"

		end 
	end

	#i want to show the edit on an individual page 

	def edit
		#lets find the story based on the url
		@story = Story.find(params[:id])

		
	end


	#i want to update the database with the updated data
	def update
		@story = Story.find(params[:id])

		# update the record with form data IF TIT VALIDATES
		if 	
			@story.update(story_params)

			flash[:sucess] ='updated well done'

			# lets make this go back to the story page/show page
			redirect_to story_path(@story)

		else 
			# if it does not update, shoe the edit form with errors
			render "edit"
		end
	end

	# lets destroy this story

	def destroy
		@story = Story.find(params[:id])

		# destroy the record with form data 
		@story.destroy

		flash[:sucess] = "its gone bye bye"

		# lets make this go back to the home page/show page
		redirect_to root_path(@story)
		
	end

	#I want to get the right data from the form

	def story_params
		# only get the title, desc and link from the story params
		params.require(:story).permit(:title, :description, :link)
		
	end

	def list
	  @stories = story.page(params[:page])
	end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

	def create

				# find the story you want to vote on 
				@story = Story.find(params[:story_id])

				# make a vote on the story with the users ip address
				@vote = @story.votes.new(ip_address: request.ip)

				# save the story if we have not voted before 
				if @vote.save

					# let the user know 
				flash[:sucess] = "you have created a vote"

				else

				# let the user know there can vote again
				flash[:error] = "you can't vote again"

				end

				

				# go back to the story page
				redirect_to story_path(@story)
		
			
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/new.html.erb
<h2>Add a comment</h2>

<%= simple_form_for [@story, @comment] do |form| %>

	<%= form.input :body,label: 'comment' %>

	<%= form.button :submit %>

<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>


	<head>
		<meta charset="utf-8">
		<title>TestingTimes</title>
		<%= stylesheet_link_tag		"application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>

		<header>
      <h1>
        <%= link_to image_tag("/assets/stack-logo.png"), root_path %>
      </h1>


<!-- you can add extra info to the url sort: "recent")-->
      <nav class = "list1">
        <%= link_to "Top", root_path %>
        <%= link_to "Recent", root_path(sort: "recent") %>
        <%= link_to "featured", root_path(filter: "featured") %>

        <%= link_to "Submit", new_story_path %>
      </nav>

    </header>

      
    <article>

      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>

      <%= yield %>
    </article>

	</body>
</html>

app/views/stories/_form.html.erb
<%= simple_form_for @story do |form| %>


<%= form.input :title %>
<%= form.input :description %>
<%= form.input :link %>

<%= form.button :submit %>

<% end %>

app/views/stories/edit.html.erb
<h1>Edit this story</h1>

<%= render "form" %>

app/views/stories/index.html.erb
<h2>TestingTimes</h2>

<!-- <p>This is my home page</p> -->

<%= paginate @stories %>
 
 <%# Time.now %>

The user currently logged in is <%= @username %>

<h2>There are <%= @stories.size %> stories</h2>

<!-- this creates loop-->

<% @stories.each do |story| %>
 

	<div class="story">
		<h3><%= link_to story.title, story.link %></h3>
		<p><%= story.description %></p>
		<p>posted <%= time_ago_in_words story.created_at %></p>
		<p>
			<%= link_to pluralize(story.comments.size, "comments"), 
						story_path(story) %>

			<%= pluralize(story.votes.size, "votes") %>
		</p>
	</div>





<% end %> 

<p>
	<%# link_to "Add a story", "/stories/new" %>
	<%= link_to "Add a story", new_story_path %>
</p>

app/views/stories/new.html.erb
<h1>Add new story</h1>

<%= render "form" %> 

app/views/stories/show.html.erb
<h1><%= @story.title %> </h1>



<p>
	<%= link_to "Edit", edit_story_path(@story), class: "Edit" %>

	<%= link_to	"Delete", story_path(@story), 
				method: :delete,	
				confirm: "are you sure?" %> 

</p>



<h3>
	<%= pluralize @story.votes.size, "vote" %>
</h3>

<p>

<%= link_to "upvote",
			story_votes_path(@story),
			method: :post %>

</p>


<h3>

	<%= pluralize @story.comments.size, "comment" %>  

</h3>
 <!-- the loop -->
<% @story.comments.each do |comment| %>

	<div class="comment" >
		<%= simple_format comment.body %>
	<p>
		<%= time_ago_in_words comment.created_at %> ago
	</p>

	</div>

 <% end %>

<p>

	<%= link_to "add a comment", new_story_comment_path(@story) %>
</p>